# Generated by Django 3.2.15 on 2022-10-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placebooking',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
