# Generated by Django 3.2.15 on 2022-10-12 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0003_alter_placebooking_date_for_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='placebooking',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='auth.user'),
            preserve_default=False,
        ),
    ]
