# Generated by Django 3.2.15 on 2022-10-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_alter_placebooking_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='name',
        ),
        migrations.AlterField(
            model_name='review',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
